version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: educonnect-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: educonnect_dev
      MYSQL_USER: educonnect
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init:/docker-entrypoint-initdb.d
    networks:
      - educonnect-network

  redis:
    image: redis:7-alpine
    container_name: educonnect-redis-dev
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - educonnect-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: educonnect-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://educonnect:password@mysql:3306/educonnect_dev
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-jwt-secret-key
      PORT: 3001
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mysql
      - redis
    networks:
      - educonnect-network
    command: pnpm dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: educonnect-frontend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001/api/v1
      NEXT_PUBLIC_SOCKET_URL: http://localhost:3001
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - educonnect-network
    command: pnpm dev

volumes:
  mysql_data:
  redis_data:

networks:
  educonnect-network:
    driver: bridge
